package com.model;

// Generated 11 oct. 2013 15:37:31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table( name = "admin"
        , schema = "public" )
public class Admin implements java.io.Serializable {

    private int    idAdmin;
    private String motPasse;
    private String login;

    public Admin() {
    }

    public Admin( int idAdmin ) {
        this.idAdmin = idAdmin;
    }

    public Admin( int idAdmin, String motPasse, String login ) {
        this.idAdmin = idAdmin;
        this.motPasse = motPasse;
        this.login = login;
    }

    @Id
    @Column( name = "id_admin", unique = true, nullable = false )
    @GenericGenerator( name = "kaugen", strategy = "increment" )
    @GeneratedValue( generator = "kaugen" )
    public int getIdAdmin() {
        return this.idAdmin;
    }

    public void setIdAdmin( int idAdmin ) {
        this.idAdmin = idAdmin;
    }

    @Column( name = "mot_passe" )
    public String getMotPasse() {
        return this.motPasse;
    }

    public void setMotPasse( String motPasse ) {
        this.motPasse = motPasse;
    }

    @Column( name = "login" )
    public String getLogin() {
        return this.login;
    }

    public void setLogin( String login ) {
        this.login = login;
    }

}
