package com.model;

// Generated 11 oct. 2013 15:37:31 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Bien generated by hbm2java
 */
@Entity
@Table( name = "bien"
        , schema = "public" )
public class Bien implements java.io.Serializable {

    private int          idBien;
    private Integer      nbPiece;
    private Integer      fourchetePrix;
    private Integer      fourcheteSurface;
    private Set<Annonce> annonces = new HashSet<Annonce>( 0 );

    public Bien() {
    }

    public Bien( int idBien ) {
        this.idBien = idBien;
    }

    public Bien( int idBien, Integer nbPiece, Integer fourchetePrix, Integer fourcheteSurface, Set<Annonce> annonces ) {
        this.idBien = idBien;
        this.nbPiece = nbPiece;
        this.fourchetePrix = fourchetePrix;
        this.fourcheteSurface = fourcheteSurface;
        this.annonces = annonces;
    }

    @Id
    @Column( name = "id_bien", unique = true, nullable = false )
    @GenericGenerator( name = "kaugen", strategy = "increment" )
    @GeneratedValue( generator = "kaugen" )
    public int getIdBien() {
        return this.idBien;
    }

    public void setIdBien( int idBien ) {
        this.idBien = idBien;
    }

    @Column( name = "nb_piece" )
    public Integer getNbPiece() {
        return this.nbPiece;
    }

    public void setNbPiece( Integer nbPiece ) {
        this.nbPiece = nbPiece;
    }

    @Column( name = "fourchete_prix" )
    public Integer getFourchetePrix() {
        return this.fourchetePrix;
    }

    public void setFourchetePrix( Integer fourchetePrix ) {
        this.fourchetePrix = fourchetePrix;
    }

    @Column( name = "fourchete_surface" )
    public Integer getFourcheteSurface() {
        return this.fourcheteSurface;
    }

    public void setFourcheteSurface( Integer fourcheteSurface ) {
        this.fourcheteSurface = fourcheteSurface;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "bien" )
    public Set<Annonce> getAnnonces() {
        return this.annonces;
    }

    public void setAnnonces( Set<Annonce> annonces ) {
        this.annonces = annonces;
    }

}
