package com.model;

// Generated 11 oct. 2013 15:37:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Filtre generated by hbm2java
 */
@Entity
@Table( name = "filtre"
        , schema = "public" )
public class Filtre implements java.io.Serializable {

    private int         idFiltre;
    private Utilisateur utilisateur;
    private String      typeAnnonce;
    private String      typeBien;
    private String      localisationBien;
    private Date        datePublication;
    private Integer     nbPiece;
    private Integer     intervalPrix;
    private Integer     intervalSurface;
    private String      termeDescription;
    private Boolean     etatFiltre;

    public Filtre() {
    }

    public Filtre( int idFiltre, Utilisateur utilisateur ) {
        this.idFiltre = idFiltre;
        this.utilisateur = utilisateur;
    }

    public Filtre( int idFiltre, Utilisateur utilisateur, String typeAnnonce, String typeBien, String localisationBien,
            Date datePublication, Integer nbPiece, Integer intervalPrix, Integer intervalSurface,
            String termeDescription, Boolean etatFiltre ) {
        this.idFiltre = idFiltre;
        this.utilisateur = utilisateur;
        this.typeAnnonce = typeAnnonce;
        this.typeBien = typeBien;
        this.localisationBien = localisationBien;
        this.datePublication = datePublication;
        this.nbPiece = nbPiece;
        this.intervalPrix = intervalPrix;
        this.intervalSurface = intervalSurface;
        this.termeDescription = termeDescription;
        this.etatFiltre = etatFiltre;
    }

    @Id
    @Column( name = "id_filtre", unique = true, nullable = false )
    @GenericGenerator( name = "kaugen", strategy = "increment" )
    @GeneratedValue( generator = "kaugen" )
    public int getIdFiltre() {
        return this.idFiltre;
    }

    public void setIdFiltre( int idFiltre ) {
        this.idFiltre = idFiltre;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "id_user", nullable = false )
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }

    public void setUtilisateur( Utilisateur utilisateur ) {
        this.utilisateur = utilisateur;
    }

    @Column( name = "type_annonce" )
    public String getTypeAnnonce() {
        return this.typeAnnonce;
    }

    public void setTypeAnnonce( String typeAnnonce ) {
        this.typeAnnonce = typeAnnonce;
    }

    @Column( name = "type_bien" )
    public String getTypeBien() {
        return this.typeBien;
    }

    public void setTypeBien( String typeBien ) {
        this.typeBien = typeBien;
    }

    @Column( name = "localisation_bien" )
    public String getLocalisationBien() {
        return this.localisationBien;
    }

    public void setLocalisationBien( String localisationBien ) {
        this.localisationBien = localisationBien;
    }

    @Temporal( TemporalType.DATE )
    @Column( name = "date_publication", length = 13 )
    public Date getDatePublication() {
        return this.datePublication;
    }

    public void setDatePublication( Date datePublication ) {
        this.datePublication = datePublication;
    }

    @Column( name = "nb_piece" )
    public Integer getNbPiece() {
        return this.nbPiece;
    }

    public void setNbPiece( Integer nbPiece ) {
        this.nbPiece = nbPiece;
    }

    @Column( name = "interval_prix" )
    public Integer getIntervalPrix() {
        return this.intervalPrix;
    }

    public void setIntervalPrix( Integer intervalPrix ) {
        this.intervalPrix = intervalPrix;
    }

    @Column( name = "interval_surface" )
    public Integer getIntervalSurface() {
        return this.intervalSurface;
    }

    public void setIntervalSurface( Integer intervalSurface ) {
        this.intervalSurface = intervalSurface;
    }

    @Column( name = "terme_description" )
    public String getTermeDescription() {
        return this.termeDescription;
    }

    public void setTermeDescription( String termeDescription ) {
        this.termeDescription = termeDescription;
    }

    @Column( name = "etat_filtre" )
    public Boolean getEtatFiltre() {
        return this.etatFiltre;
    }

    public void setEtatFiltre( Boolean etatFiltre ) {
        this.etatFiltre = etatFiltre;
    }

}
