package com.model;

// Generated 11 oct. 2013 15:37:31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Statistique generated by hbm2java
 */
@Entity
@Table( name = "statistique"
        , schema = "public" )
public class Statistique implements java.io.Serializable {

    private int         idStat;
    private Utilisateur utilisateur;
    private Integer     nbAnnonce;
    private Integer     nbFiltreActif;

    public Statistique() {
    }

    public Statistique( int idStat, Utilisateur utilisateur ) {
        this.idStat = idStat;
        this.utilisateur = utilisateur;
    }

    public Statistique( int idStat, Utilisateur utilisateur, Integer nbAnnonce, Integer nbFiltreActif ) {
        this.idStat = idStat;
        this.utilisateur = utilisateur;
        this.nbAnnonce = nbAnnonce;
        this.nbFiltreActif = nbFiltreActif;
    }

    @Id
    @Column( name = "id_stat", unique = true, nullable = false )
    @GenericGenerator( name = "kaugen", strategy = "increment" )
    @GeneratedValue( generator = "kaugen" )
    public int getIdStat() {
        return this.idStat;
    }

    public void setIdStat( int idStat ) {
        this.idStat = idStat;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "id_user", nullable = false )
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }

    public void setUtilisateur( Utilisateur utilisateur ) {
        this.utilisateur = utilisateur;
    }

    @Column( name = "nb_annonce" )
    public Integer getNbAnnonce() {
        return this.nbAnnonce;
    }

    public void setNbAnnonce( Integer nbAnnonce ) {
        this.nbAnnonce = nbAnnonce;
    }

    @Column( name = "nb_filtre_actif" )
    public Integer getNbFiltreActif() {
        return this.nbFiltreActif;
    }

    public void setNbFiltreActif( Integer nbFiltreActif ) {
        this.nbFiltreActif = nbFiltreActif;
    }

}
