package com.model;

// Generated 11 oct. 2013 15:37:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table( name = "utilisateur"
        , schema = "public" )
public class Utilisateur implements java.io.Serializable {

    private int              idUser;
    private String           alias;
    private String           name;
    private String           prenom;
    private String           email;
    private Date             dateInscri;
    private Set<Annonce>     annonces     = new HashSet<Annonce>( 0 );
    private Set<Statistique> statistiques = new HashSet<Statistique>( 0 );
    private Set<Filtre>      filtres      = new HashSet<Filtre>( 0 );

    public Utilisateur() {
    }

    public Utilisateur( int idUser ) {
        this.idUser = idUser;
    }

    public Utilisateur( int idUser, String alias, String name, String prenom, String email, Date dateInscri,
            Set<Annonce> annonces, Set<Statistique> statistiques, Set<Filtre> filtres ) {
        this.idUser = idUser;
        this.alias = alias;
        this.name = name;
        this.prenom = prenom;
        this.email = email;
        this.dateInscri = dateInscri;
        this.annonces = annonces;
        this.statistiques = statistiques;
        this.filtres = filtres;
    }

    @Id
    @Column( name = "id_user", unique = true, nullable = false )
    @GenericGenerator( name = "kaugen", strategy = "increment" )
    @GeneratedValue( generator = "kaugen" )
    public int getIdUser() {
        return this.idUser;
    }

    public void setIdUser( int idUser ) {
        this.idUser = idUser;
    }

    @Column( name = "alias" )
    public String getAlias() {
        return this.alias;
    }

    public void setAlias( String alias ) {
        this.alias = alias;
    }

    @Column( name = "name" )
    public String getName() {
        return this.name;
    }

    public void setName( String name ) {
        this.name = name;
    }

    @Column( name = "prenom" )
    public String getPrenom() {
        return this.prenom;
    }

    public void setPrenom( String prenom ) {
        this.prenom = prenom;
    }

    @Column( name = "email" )
    public String getEmail() {
        return this.email;
    }

    public void setEmail( String email ) {
        this.email = email;
    }

    @Temporal( TemporalType.DATE )
    @Column( name = "date_inscri", length = 13 )
    public Date getDateInscri() {
        return this.dateInscri;
    }

    public void setDateInscri( Date dateInscri ) {
        this.dateInscri = dateInscri;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "utilisateur" )
    public Set<Annonce> getAnnonces() {
        return this.annonces;
    }

    public void setAnnonces( Set<Annonce> annonces ) {
        this.annonces = annonces;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "utilisateur" )
    public Set<Statistique> getStatistiques() {
        return this.statistiques;
    }

    public void setStatistiques( Set<Statistique> statistiques ) {
        this.statistiques = statistiques;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "utilisateur" )
    public Set<Filtre> getFiltres() {
        return this.filtres;
    }

    public void setFiltres( Set<Filtre> filtres ) {
        this.filtres = filtres;
    }

}
